/* Trips stores each travel library in IndexedDB on this device. */
const DB = 'trips-library';
const STORE = 'library';
const KEY = 'state';
const COLOURS = ['#9eaa84','#d8a648','#a75d55','#6e8f88','#90788f'];
const tabs = [['overview','Overview'],['itinerary','Itinerary'],['diary','Diary'],['bookings','Bookings'],['transport','Transport'],['packing','Packing'],['shopping','Shopping'],['conditions','Conditions'],['outfits','Outfits'],['journal','Journal']];
const configs = {
  itinerary: {title:'Build the itinerary', note:'Add the backbone of every day, including activities, buffers and things you need to check.', fields:[['title','What is happening?','text',1],['date','Date','date'],['time','Time','time'],['place','Place','text'],['status','Status','select',['Planned','Booked','Idea','Done']],['cost','Cost','number'],['details','Route, timing or useful notes','textarea']]},
  diary: {title:'Daily diary', note:'For what actually happened, rather than the plan.', fields:[['title','Heading','text',1],['date','Date','date'],['details','Entry','textarea',1],['attachment','Photo or scan','file']]},
  bookings: {title:'Booking wallet', note:'Save ticket details, confirmation files and booking conditions together.', fields:[['title','Booking, stay or activity','text',1],['type','Type','select',['Hostel / stay','Attraction','Transport ticket','Tour','Reservation','Other']],['provider','Provider','text'],['date','Date','date'],['time','Time','time'],['reference','Reference number','text'],['cost','Paid','number'],['details','Conditions or useful details','textarea'],['attachment','Attach ticket or booking file','file']]},
  transport: {title:'Route maker', note:'Add each door-to-door leg in order. Keep the actual ticket in Bookings.', fields:[['title','Route title','text',1],['from','From','text',1],['to','To','text',1],['date','Date','date'],['depart','Depart','time'],['arrive','Arrive','time'],['method','Method','select',['Walk','Bus','Train','Metro','Flight','Ferry','Taxi','Other']],['cost','Expected cost','number'],['details','Instructions or fallback','textarea']]},
  packing: {title:'Packing list', note:'Tick items only when they are physically in the bag.', fields:[['title','Item','text',1],['category','Category','text'],['quantity','Quantity','number'],['details','Note','textarea']]},
  shopping: {title:'Shopping list', note:'Add where or when you expect to find the thing, not just the thing itself.', fields:[['title','Item','text',1],['category','Category','text'],['where','Where or when','text'],['price','Target price','number'],['details','Specific requirements','textarea']]},
  conditions: {title:'Attraction conditions', note:'Use this for entry rules, clothing, timing and practical requirements.', fields:[['title','Place or activity','text',1],['status','Booking state','select',['Not booked','Booked','Need to check','Walk-in possible']],['rules','Entry rules','textarea'],['wear','Bring or wear','textarea'],['details','Weather, access or route notes','textarea']]},
  outfits: {title:'Outfit planner', note:'Keep clothes, their purpose and a visual reference together.', fields:[['title','Outfit name','text',1],['occasion','Best for or date','text'],['pieces','Pieces','textarea'],['details','Practical notes','textarea'],['attachment','Add photo','file']]},
  journal: {title:'Travel journal', note:'Pages for after the planning is over and you want the trip to stay on the shelf.', fields:[['title','Title','text',1],['date','Date','date'],['details','Journal entry','textarea',1],['attachment','Attach photo or scan','file']]}
};
let db, state={trips:[],activeTripId:null}, activeTab='overview', saveTimer, saveMessage='Saved on this device';
const $ = s => document.querySelector(s);
const id = p => `${p}_${crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2)}`;
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const safe = v => esc(v).replace(/\n/g,'<br>');
const today = () => new Date().toISOString().slice(0,10);
const isDate = v => /^\d{4}-\d{2}-\d{2}$/.test(v||'');
const fmtDate = v => isDate(v) ? new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00`)) : (v||'');
const price = v => v === '' || v == null ? '' : `€${Number(v).toFixed(2).replace(/\.00$/,'')}`;
const trip = () => state.trips.find(x=>x.id===state.activeTripId);

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function read(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function write(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,KEY);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
function save(message='Saved on this device'){saveMessage='Saving…';status();clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await write();saveMessage=message}catch(e){console.error(e);saveMessage='Could not save'}status()},250)}
function fileURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type||'application/octet-stream',data:r.result});r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function newTrip(data){return {id:id('trip'),title:data.title||'Untitled trip',destinations:data.destinations||'',startDate:data.startDate||'',endDate:data.endDate||'',coverNote:data.coverNote||'',overview:'',colour:COLOURS[Math.floor(Math.random()*COLOURS.length)],itinerary:[],diary:[],bookings:[],transport:[],packing:[],shopping:[],conditions:[],outfits:[],journal:[]}}
async function publishedState(){try{const response=await fetch('./data/andalusia-2026.js',{cache:'no-store'});if(!response.ok)throw Error('No published trip file');const source=(await response.text()).replace(/T-shirts/g,'T shirts');const scope={};Function('window',source)(scope);return scope.TRIPS_PUBLISHED_STATE}catch(error){console.error(error);return null}}
async function seedPublishedTrip(){const published=await publishedState();if(!published?.trips?.length)return;const exists=state.trips.some(x=>x.id==='andalusia-2026');if(exists)return;state=state.trips.length?{trips:[...state.trips,...published.trips],activeTripId:published.activeTripId}:published;await write();saveMessage='Published Andalusia 2026 imported'}

function shelf(){return state.trips.length?state.trips.map(x=>`<button class="shelf-trip ${x.id===state.activeTripId?'active':''}" style="--book-colour:${esc(x.colour)}" data-act="select" data-id="${x.id}"><strong>${esc(x.title)}</strong><span>${esc(x.destinations||'Destination pending')}</span></button>`).join(''):'<p class="form-note" style="padding:0 10px">Your finished and future trips will live here.</p>'}
function status(){const box=$('#storage-status');if(box)box.innerHTML=`<p class="storage-status"><span class="status-dot"></span>${esc(saveMessage)}. Changes save on this device.</p><div class="sidebar-actions"><button class="ghost" data-act="export">Export backup</button><button class="ghost" data-act="import">Import backup</button></div>`}
function header(t){const dates=t.startDate||t.endDate?`${t.startDate?fmtDate(t.startDate):'Date TBD'}${t.endDate?' – '+fmtDate(t.endDate):''}`:'Dates to be decided';return `<div class="topbar"><div><p class="eyebrow">${esc(t.destinations||'TRIP VOLUME')}</p><h1>${esc(t.title)}</h1><p class="trip-meta">${esc(dates)}</p></div><button class="secondary" data-act="delete-trip">Archive this trip</button></div><nav class="nav-tabs">${tabs.map(([k,label])=>`<button class="nav-tab ${activeTab===k?'active':''}" data-tab="${k}">${label}</button>`).join('')}</nav>`}
function noTrip(){return `<div class="topbar"><div><p class="eyebrow">YOUR TRAVEL LIBRARY</p><h1>Plan now, remember it later.</h1><p class="trip-meta">One travel volume per trip, with room for the practical bits and the actual memories.</p></div></div>${empty('Your shelf is waiting','Start a trip to build the itinerary, keep booking files, make lists, record routes and keep your journal in one place.','Start a trip','new-trip')}`}
function empty(title,copy,label,action){return `<section class="empty"><div class="mini-mark">T</div><h2>${esc(title)}</h2><p>${esc(copy)}</p>${action?`<button class="primary" data-act="${action}">${esc(label)}</button>`:''}</section>`}
function overview(t){const packed=t.packing.filter(x=>x.done).length;const upcoming=[...t.itinerary].sort((a,b)=>`${a.date||'9999'}${a.time||''}`.localeCompare(`${b.date||'9999'}${b.time||''}`)).slice(0,4);return `<div class="dashboard-grid"><section class="card summary-card"><p class="eyebrow">THE CURRENT VOLUME</p><h2>${esc(t.coverNote||'A trip with its plans, papers and memories kept together.')}</h2><p>${esc(t.destinations||'Add destinations, dates and all the useful details as you plan.')}</p></section><div class="stats-grid"><section class="card stat"><span class="number">${t.itinerary.length}</span><span class="label">ITINERARY BLOCKS</span></section><section class="card stat"><span class="number">${t.bookings.length}</span><span class="label">BOOKINGS SAVED</span></section><section class="card stat"><span class="number">${packed}/${t.packing.length}</span><span class="label">PACKING READY</span></section><section class="card stat"><span class="number">${t.diary.length+t.journal.length}</span><span class="label">MEMORY ENTRIES</span></section></div><section class="card card-pad notes-card"><div class="section-head"><div><h3>Trip notes</h3><p>Updates save as you type.</p></div><span class="chip">Autosave on</span></div><textarea data-live="overview" rows="5" placeholder="Keep decisions, reminders and questions for later here.">${esc(t.overview)}</textarea></section><section class="card card-pad"><div class="section-head"><div><h3>Next in the plan</h3><p>Your earliest itinerary blocks.</p></div><button class="ghost" data-tab="itinerary">See itinerary</button></div>${upcoming.length?`<div class="timeline">${upcoming.map(x=>`<div class="timeline-item"><div class="timeline-time">${esc(x.date?fmtDate(x.date):'DATE TBD')}${x.time?' · '+esc(x.time):''}</div><div class="timeline-title">${esc(x.title)}</div><p class="timeline-text">${esc([x.place,x.status,x.details].filter(Boolean).join(' · '))}</p></div>`).join('')}</div>`:'<p class="form-note">Add your first block to see the plan building here.</p>'}</section><section class="card card-pad"><div class="section-head"><div><h3>Published trip record</h3></div></div><p class="form-note">Andalusia 2026 is seeded from the public repository by request. The itinerary, booking references and practical travel information in that volume are public. Changes made after import remain saved in this browser until you export a backup.</p><button class="secondary" data-act="export">Export backup</button></section></div>`}
function input(field){const [name,label,type,options]=field;const required=options===1?'required':'';const ph=type==='text'?`placeholder="${esc(label)}"`:'';if(type==='textarea')return `<label>${label}<textarea name="${name}" rows="4" ${required}></textarea></label>`;if(type==='select')return `<label>${label}<select name="${name}">${options.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`;if(type==='file')return `<label>${label}<input name="${name}" type="file" accept="image/*,application/pdf,.pkpass" /></label>`;return `<label>${label}<input name="${name}" type="${type}" ${type==='number'?'min="0" step="0.01"':''} ${ph} ${required} /></label>`}
function form(key){const c=configs[key];return `<section class="card editor"><h2>${esc(c.title)}</h2><p class="form-note">${esc(c.note)}</p><form data-form="${key}">${c.fields.map(input).join('')}<button class="primary" type="submit">Save ${key==='itinerary'?'to itinerary':key.slice(0,-1)||key}</button></form></section>`}
function meta(x,key){const c=configs[key];return c.fields.filter(([n,,type])=>!['title','textarea','file'].includes(type)&&x[n]).map(([n,label])=>`<span>${esc(label)}: ${esc(n==='date'?fmtDate(x[n]):n==='cost'||n==='price'?price(x[n]):x[n])}</span>`).join('')}
function textFields(x,key){return configs[key].fields.filter(([n,,type])=>type==='textarea'&&x[n]).map(([n,label])=>`<p><strong>${esc(label)}:</strong> ${safe(x[n])}</p>`).join('')}
function attachment(x){if(!x.attachment)return '';const src=x.attachment.url||x.attachment.data;if(!src)return '';return `${x.attachment.type?.startsWith('image/')?`<img class="photo-thumb" src="${src}" alt="Attached reference" />`:''}<a class="attachment-button" href="${src}" download="${esc(x.attachment.name||'attachment')}" target="_blank" rel="noopener">Open ${esc(x.attachment.name||'attachment')}</a>`}
function list(t,key){let items=[...t[key]];if(key==='itinerary'||key==='transport'||key==='bookings'||key==='diary'||key==='journal')items.sort((a,b)=>`${a.date||'9999'}${a.time||a.depart||''}`.localeCompare(`${b.date||'9999'}${b.time||b.depart||''}`));if(key==='packing'||key==='shopping')items.sort((a,b)=>Number(a.done)-Number(b.done));if(!items.length)return empty(`No ${key} yet`,configs[key].note,'','');return `<div class="content-stack">${items.map(x=>{const check=(key==='packing'||key==='shopping')?`<input type="checkbox" data-done="${key}" data-id="${x.id}" ${x.done?'checked':''} aria-label="Mark done" />`:'';return `<article class="card entry ${check?'check-row':''}">${check}<div><div class="entry-header"><div><h3 class="${x.done?'done':''}">${esc(x.title)}</h3><div class="entry-meta">${meta(x,key)}</div></div><div class="entry-actions"><button class="ghost" data-act="remove" data-key="${key}" data-id="${x.id}">Remove</button></div></div>${key==='transport'?`<p><strong>${esc(x.from)}</strong> → <strong>${esc(x.to)}</strong></p>`:''}${textFields(x,key)}${attachment(x)}</div></article>`}).join('')}</div>`}
function section(t,key){return `<div class="editor-grid">${form(key)}<section><div class="section-head"><div><h2>${key[0].toUpperCase()+key.slice(1)}</h2><p>${t[key].length} saved</p></div></div>${list(t,key)}</section></div>`}
function view(t){return activeTab==='overview'?overview(t):section(t,activeTab)}
function render(){const t=trip();$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">T</span><div><strong class="brand-name">Trips</strong><small>Travel library</small></div></div><button class="primary new-trip" data-act="new-trip">+ Start a trip</button><div class="trip-shelf-heading"><p>Your shelf</p><span class="chip">${state.trips.length} ${state.trips.length===1?'trip':'trips'}</span></div><div class="shelf-list">${shelf()}</div><div class="sidebar-footer" id="storage-status"></div></aside><main class="workspace">${t?header(t)+view(t):noTrip()}</main></div>`;status()}

async function submit(e){e.preventDefault();const f=e.target,key=f.dataset.form;if(!key)return;const t=trip();const item={id:id(key),done:false};for(const [name,,type] of configs[key].fields){if(type==='file'){const file=f.elements[name].files[0];if(file)item.attachment=await fileURL(file)}else item[name]=f.elements[name].value.trim()}t[key].push(item);save();render()}
function click(e){const b=e.target.closest('[data-act],[data-tab]');if(!b)return;if(b.dataset.tab){activeTab=b.dataset.tab;render();return}const act=b.dataset.act;if(act==='new-trip')$('#trip-dialog').showModal();if(act==='close-dialog')$('#trip-dialog').close();if(act==='select'){state.activeTripId=b.dataset.id;activeTab='overview';save();render()}if(act==='delete-trip'){const t=trip();if(t&&confirm(`Archive “${t.title}” from this device?`)){state.trips=state.trips.filter(x=>x.id!==t.id);state.activeTripId=state.trips[0]?.id||null;save();render()}}if(act==='remove'){const t=trip();if(confirm('Remove this item?')){t[b.dataset.key]=t[b.dataset.key].filter(x=>x.id!==b.dataset.id);save();render()}}if(act==='export')exportBackup();if(act==='import')$('#backup-import').click()}
function change(e){const x=e.target;if(!x.dataset.done)return;const t=trip(),item=t[x.dataset.done].find(y=>y.id===x.dataset.id);if(item){item.done=x.checked;save();render()}}
function typing(e){const x=e.target;if(!x.dataset.live)return;trip()[x.dataset.live]=x.value;save()}
function download(name,data){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportBackup(){try{await write();download(`trips-backup-${today()}.json`,JSON.stringify({app:'Trips',version:1,exportedAt:new Date().toISOString(),state}));saveMessage='Backup downloaded. Keep it private.'}catch(e){console.error(e);saveMessage='Backup failed'}status()}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(data.app!=='Trips'||!data.state?.trips)throw Error();if(!confirm('Replace the trips on this browser with this backup?'))return;state=data.state;activeTab='overview';await write();saveMessage='Backup restored';render()}catch(e){alert('That was not a Trips backup.')}}
async function init(){try{db=await openDB();state=await read()||state;await seedPublishedTrip();if(state.trips.length&&!trip())state.activeTripId=state.trips[0].id;render()}catch(e){console.error(e);$('#app').innerHTML='<main class="workspace">Storage could not open. Use a normal browser tab rather than private browsing.</main>'}$('#app').addEventListener('click',click);$('#app').addEventListener('submit',submit);$('#app').addEventListener('change',change);$('#app').addEventListener('input',typing);$('#trip-dialog').addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(f.id!=='new-trip-form')return;const t=newTrip(Object.fromEntries(new FormData(f)));state.trips.unshift(t);state.activeTripId=t.id;activeTab='overview';$('#trip-dialog').close();save();render()});$('#backup-import').addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=''});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init();
